name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"   # runs every day at midnight UTC
  workflow_dispatch:      # lets you trigger manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: Jiyo-pv   # <-- your username
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push Snake to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
